[package]
name = "plugin_model_sandbox"
version = "0.1.0"
authors = ["hkrn <129939+hkrn@users.noreply.github.com>"]
edition = "2018"

[dependencies]
nanoem-core = { path = "../core" }
nanoem-protobuf = { path = "../protobuf" }

[lib]
path = "src/lib.rs"
crate-type = [ "cdylib" ]
