[workspace]
members = [
    "core",
    "main",
    "plugin_debugger",
    "plugin_model_sandbox",
    "plugin_motion_sandbox",
    "plugin_wasm",
    "protobuf"
]
exclude = [
    "wasm",
    "viewer",
]
