[package]
name = "plugin_wasm"
version = "0.1.0"
authors = ["hkrn <129939+hkrn@users.noreply.github.com>"]
edition = "2018"

[dependencies]
hotwatch = "0.4"
wasmer-runtime = "0.17"
wasmer-wasi = "0.17"

[lib]
path = "src/lib.rs"
crate-type = [ "cdylib" ]
