[package]
name = "nanoem-core"
version = "0.1.0"
authors = ["hkrn <129939+hkrn@users.noreply.github.com>"]
edition = "2018"
build = "build.rs"
links = "nanoem"

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1.0"

[lib]
name = "nanoem"
path = "src/nanoem/lib.rs"
